name: LoadBalancer
main: ifteam\LoadBalancer\LoadBalancer
version: 0.1-Alpha
author: ifteam
api: [1.12.0]

permissions:
 loadbalancer.control:
  default: OP
  description: "Operate the load balancer"