name: LoadBalancer
main: ifteam\LoadBalancer\LoadBalancer
version: 0.5-Alpha
author: ifteam
api:
- 1.13.0
- 2.0.0

permissions:
 loadbalancer.control:
  default: OP
  description: "Operate the load balancer"